# golangci-lint v2.1.6 configuration
version: "2"

run:
  go: "1.21"
  timeout: 5m

linters:
  enable:
    - errcheck     # Check for unchecked errors
    - govet        # Go vet examiner  
    - ineffassign  # Detect ineffectual assignments
    - misspell     # Finds commonly misspelled English words
    - revive       # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - staticcheck  # Static analysis checks
    - unused       # Check for unused constants, variables, functions and types
    - gocritic     # Provides diagnostics that check for bugs, performance and style issues
    - unconvert    # Remove unnecessary type conversions

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
